read -p "Enter Origin: " origin
read -p "Enter Destination: " dest
read -p "Enter Year: " year
read -p "Enter Month: " month
read -p "Enter Day: " day

###ASTERIXDB###

curl -v --data-urlencode "statement=CREATE TYPE data_type AS OPEN{id:uuid,year:int,month:int, day:int, unique_carrier:String,origin:String, dest:String, dep_time:float, dep_delay_new:float, arr_time:float,arr_delay:float, actual_elapsed_time:float, carrier_delay:float,rank:float};" http://localhost:19002/query/service  

curl -v --data-urlencode "statement= CREATE DATASET data_set (datat_type) PRIMARY KEY id AUTOGENERATED;" http://localhost:19002/query/service

curl -v --data-urlencode "statement=LOAD DATASET data_set USING localfs (('path'='127.0.0.1:///opt/hadoop/home/hadoop3/Project/CleanData/ranking.csv'), ('format'='delimited-text'));" http://localhost:19002/query/service

#curl -v --data-urlencode "statement=LOAD DATASET data_set USING localfs (('path'='$1'), ('format'='delimited-text'));" http://localhost:19002/query/service

curl -v --data-urlencode "statement=SELECT * FROM data_set WHERE origin='$origin' and dest='$dest' and year='$year' and month='$month' and day='$day' ORDER BY rank;" http://localhost:19002/query/service


###MONGO###
mongoimport --db bigData --collection search_engine --type csv --file /home/hdp/Desktop/CleanData/ranking.csv --headerline

mongo --eval "db.search_engine.find({origin:'$origin', dest:'$dest', year:'$year', month:'$month', day:'$day'}).sort({'RANK':1}).pretty();"

